# Generated by Django 2.1.5 on 2019-01-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=5000)),
                ('file', models.ImageField(upload_to='report_images')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('confrimed', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
