# Generated by Django 2.1.5 on 2019-01-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyewitness', '0002_auto_20190117_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pub',
            field=models.BooleanField(default=False),
        ),
    ]
