# Generated by Django 2.1.5 on 2019-01-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyewitness', '0003_report_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
