# Generated by Django 2.1.5 on 2019-01-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyewitness', '0004_auto_20190117_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyewitness.Report')),
            ],
        ),
    ]
