# Generated by Django 2.1.5 on 2019-01-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyewitness', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Report',
            new_name='report',
        ),
    ]
