# Generated by Django 2.1.5 on 2019-02-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyewitness', '0007_auto_20190123_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
